---
role_name_check: 1
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: ansible-debian12-test
    image: tmolnar-debian:1.4
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
lint: |
  set -e
  yamllint .
  ansible-lint
